version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - audit_db
  audit_db:
    image: codenotary/immudb:latest
    restart: unless-stopped
    ports:
      - "3322:3322"
      - "9497:9497"
    env_file:
      - .local.immudb.env
