version: "3.9"

services:
  app:
    build:
      context: .
      target: "development-image"
    ports:
      - "80:80"
    depends_on:
      - audit_db
  black-test:
    build:
      context: .
      target: "black-test-image"
  unit-tests:
    build:
      context: .
      target: "unit-test-image"
  load-tests:
    build:
      context: .
      target: "load-test-image"
  audit_db:
    image: codenotary/immudb:latest
    restart: unless-stopped
    ports:
      - "3322:3322"
      - "9497:9497"
    env_file:
      - .local.immudb.env
