# Configuration options: https://pgjones.gitlab.io/hypercorn/how_to_guides/configuring.html#how-to-configure
access_log_format = '%(h)s %(l)s %(l)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
alpn_protocols = ['h2', 'http/1.1']
backlog = 100
bind = 80
debug = True
keep_alive_timeout = 20
use_reloader = True
# The reason for uvloop is compatibility with the current code but
# we should migrate to trio
worker_class = uvloop
workers = 4